config/routes.rb
WhoAround::Application.routes.draw do
  
  devise_for :users, :skip => :all
  devise_scope :user do
    namespace :auth do
      post :sign_in,  :to => 'sessions#create'
      get  :sign_out, :to => 'sessions#destroy'
      
      post :sign_up,  :to => 'registrations#create'
    end
  end
  
  root 'home#index'
  get  'feed', :to => 'home#feed'
  get  'around_posts',  :to => 'home#around_posts'
  get  'around_events', :to => 'home#around_events'
  get  'popular_users', :to => 'home#popular_users'
  
  resources :users, :only => [:index, :show] do
    get 'subscribers', :on => :collection
    get 'publishers',  :on => :collection
    
    get 'subscribed_events', :on => :collection
    get 'published_events', :on => :collection
    
    get 'read',   :on => :collection
    get 'unread', :on => :collection
  end
  
  resources :posts, :only => [:index, :show, :create] do
    get 'feed', :on => :collection
    get 'event_feed', :on => :collection
  end
  
  resources :events, :only => [:show] do
    get 'subscribers', :on => :collection
    get 'publishers',  :on => :collection
    
    get 'read',   :on => :collection
    get 'unread', :on => :collection
  end
  
end

app/views/forms/_new_message.html.haml
- id ||= ""
- cl ||= ""
- cl += ' newMessageForm'
= form_for(Post.new, :url => posts_path(:format => :json), :method => :post, :html => { :id => id, :class => cl }) do |f|
  .form-group
    %label Text
    = f.text_area :text, :class => 'form-control'
  - unless @event
    .form-group.eventSelector
      %label Event
      .input-group
        %select.form-control{ :name => 'post[event]' }
        %span.input-group-btn
          %button.btn.btn-default.update{ :type => :button }
            %span.glyphicon.glyphicon-refresh
  - else
    %input{ :type => :hidden, :name => 'post[event]', :value => @event.id }
  
  = f.submit 'Send', :class => 'btn btn-default'

app/views/forms/_signin.html.haml
- id ||= ""
- cl ||= ""
- cl += ' ajaxForm'
= form_for(User.new, :url => auth_sign_in_path(:format => :json), :html => { :id => id, :class => cl }) do |f|
  .form-group
    %label Email
    = f.text_field :login, :class => 'form-control'
  .form-group
    %label Password
    = f.password_field :password, :class => 'form-control'
  .checkbox
    %label
      Remember me
      = f.check_box :remember_me
  = f.submit 'Sign in', :class => 'btn btn-default'

app/views/forms/_signup.html.haml
- id ||= ""
- cl ||= ""
- cl += ' ajaxForm'
= form_for(User.new, :url => auth_sign_up_path(:format => :json), :html => { :id => id, :class => cl }) do |f|
  .form-group
    %label Username
    = f.text_field :username, :class => 'form-control'
  .form-group
    %label Email
    = f.text_field :email, :class => 'form-control'
  .form-group
    %label Password
    = f.password_field :password, :class => 'form-control', :autocomplete => 'off'
  .form-group
    %label Password confirmation
    = f.password_field :password_confirmation, :class => 'form-control', :autocomplete => 'off'
  = f.submit 'Sign up', :class => 'btn btn-default'